{% set name = "skunk" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skunk-{{ version }}.tar.gz
  sha256: b5f13e8dfdc5e4db36fc7b8bb9a677dc0c9a923f1397cf553d4d3d1eb4f494bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - python >=3.6

test:
  imports:
    - skunk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/whitead/skunk
  summary: Insert SVGs into matplotlib figures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
