{% set name = "skunk" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skunk-{{ version }}.tar.gz
  sha256: 3131a4a786a879db6bd8a360a74f03be05b9a34b9e379cc5ced0f0d3ed0056ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - python >=3.6

test:
  imports:
    - skunk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/whitead/skunk
  summary: Insert SVGs into matplotlib figures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
