context:
  name: skunk
  version: 1.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/skunk-${{ version }}.tar.gz
  sha256: a42c672ad08c7d5dcf174345ee3a12bc7f2c0c7182c3c9fd75548cc7729676b6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - matplotlib-base
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - skunk
      python_version: ${{ python_min }}.*

about:
  summary: Insert SVGs into matplotlib figures
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/whitead/skunk

extra:
  recipe-maintainers:
    - hadim
